ALTER TABLE [dbo].[MGUIATRANSPORTE] DROP CONSTRAINT [PK_MGUIATRANSPORTE] WITH ( ONLINE = OFF )
GO
ALTER TABLE [dbo].[MGUIATRANSPORTE] alter column [tGuiaTransporte] varchar(16) COLLATE Modern_Spanish_CI_AS  NOT NULL
GO
ALTER TABLE [dbo].[MGUIATRANSPORTE] WITH NOCHECK ADD 
CONSTRAINT [PK_MGUIATRANSPORTE] PRIMARY KEY  CLUSTERED 
(
	[tGuiaTransporte]
)  ON  [PRIMARY] 
GO

ALTER TABLE [dbo].[DGUIATRANSPORTE] DROP CONSTRAINT PK_DGUIATRANSPORTE WITH ( ONLINE = OFF )
GO
ALTER TABLE [dbo].[DGUIATRANSPORTE] alter column [tGuiaTransporte] varchar(16) COLLATE Modern_Spanish_CI_AS  NOT NULL
GO
ALTER TABLE [dbo].[DGUIATRANSPORTE] WITH NOCHECK ADD 
	CONSTRAINT [PK_DGUIATRANSPORTE] PRIMARY KEY  CLUSTERED 
	(
		[tGuiaTransporte],
		[tItem]
	)  ON [PRIMARY] 

GO

ALTER TABLE [dbo].[DPEDIDO] alter column [tGuiaTransporte] varchar(16) COLLATE Modern_Spanish_CI_AS  NULL



