
UPDATE TTABLA SET nValor=0  WHERE ttabla='PAISORIGEN'
UPDATE TTABLA SET nValor=1  WHERE ttabla='PAISORIGEN' AND TCODIGO='004'

UPDATE TTABLA SET tResumido='US$'  WHERE ttabla='MONEDA' AND TCODIGO='02'
UPDATE TTABLA SET tResumido='CL$'  WHERE ttabla='MONEDA' AND TCODIGO='01'

UPDATE TPARAMETRO SET tMonedaN='Pesos' ,tMonN='CL$', tMonedaE='Dolares', tMonE='US$'


