
UPDATE TTABLA SET nValor=0  WHERE ttabla='PAISORIGEN'
UPDATE TTABLA SET nValor=1  WHERE ttabla='PAISORIGEN' AND TCODIGO='002'

UPDATE TTABLA SET tResumido='US$'  WHERE ttabla='MONEDA' AND TCODIGO='01'
UPDATE TTABLA SET tResumido='xxx'  WHERE ttabla='MONEDA' AND TCODIGO='02'

--UPDATE TTIPODOCUMENTOIMPRESORA SET tNumeroAutorizacion='1115006109'

UPDATE TPARAMETRO SET tMonedaN='Dolares' ,tMonN='$', tMonedaE='', tMonE=''
