
UPDATE TTABLA SET nValor=0  WHERE ttabla='PAISORIGEN'
UPDATE TTABLA SET nValor=1  WHERE ttabla='PAISORIGEN' AND TCODIGO='000'

UPDATE TTABLA SET tResumido='US$'  WHERE ttabla='MONEDA' AND TCODIGO='02'
UPDATE TTABLA SET tResumido='S/.'  WHERE ttabla='MONEDA' AND TCODIGO='01'

--UPDATE TTIPODOCUMENTOIMPRESORA SET tNumeroAutorizacion='1115006109'

UPDATE TPARAMETRO SET tMonedaN='Soles' ,tMonN='S/.', tMonedaE='Dolares', tMonE='US$'

